package br.com.fiap.traintime.enuns;

public enum CategoriaDeExercicio {
    NUNCA_FEZ_MUSCULACAO, TREINAMENTO_DE_FORCA, CARDIOVASCULAR, PERDA_DE_PESO, FLEXIBILIDADE, TREINAMENTO_FUNCIONAL,
    TREINAMENTO_DE_RESISTENCIA, TREINAMENTO_DE_EQUILIBRIO
}